################################################################################
#
# batman-adv-legacy
#
################################################################################

BATMAN_ADV_LEGACY_VERSION = 042e300adfaff2dc5a1a1bdfa09c2cfbc99a3dec
BATMAN_ADV_LEGACY_SITE_METHOD = git
BATMAN_ADV_LEGACY_SITE = https://github.com/freifunk-gluon/batman-adv-legacy.git
BATMAN_ADV_LEGACY_LICENSE = GPLv2
BATMAN_ADV_LEGACY_DEPENDENCIES = linux

define BATMAN_ADV_LEGACY_BUILD_CMDS
	$(MAKE) -C $(@D) $(LINUX_MAKE_FLAGS) KERNELPATH=$(LINUX_DIR) \
		CONFIG_BATMAN_ADV_DEBUG=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_DEBUG) \
		CONFIG_BATMAN_ADV_BLA=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_BLA) \
		CONFIG_BATMAN_ADV_DAT=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_DAT) \
		CONFIG_BATMAN_ADV_NC=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_NC)
endef

define BATMAN_ADV_LEGACY_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D) $(LINUX_MAKE_FLAGS) KERNELPATH=$(LINUX_DIR) \
		CONFIG_BATMAN_ADV_DEBUG=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_DEBUG) \
		CONFIG_BATMAN_ADV_BLA=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_BLA) \
		CONFIG_BATMAN_ADV_DAT=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_DAT) \
		CONFIG_BATMAN_ADV_NC=$(BR2_PACKAGE_BATMAN_ADV_LEGACY_NC) \
		INSTALL_MOD_PATH=$(TARGET_DIR) \
		install
endef

$(eval $(generic-package))
